### ISSUE TITLE
Couldn't find the node_modules state file

### ISSUE THREAD

**Issue by kacperpaczos** [react-gjs/react-gjs-renderer#221]
I can't build the package because I don't have node_modules despite running yarn install.
```
yarn install
yarn build
```
what am I doing wrong?

```
yarn build
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

```

**Comment by ncpa0cpl** [comment]
Looks like yarn is trying to use [PnP](https://yarnpkg.com/features/pnp) instead of the node-modules linker. Which is weird, since in the `.yarnrc.yml` file the correct linker is definitely set. After googling a little it seems that this can happen if the `yarn install` fails. Did you not get any errors when running it?

I tried to clone the repo and do the install, the damned thing stopped in the middle and couldn't finish. I've meant to switch back to yarn 1 for some time, I guess this may be the time to do it.

**Comment by kacperpaczos** [comment]
I use yarn 1.22.21....

**Comment by kacperpaczos** [comment]
Ok, I did the git pull and now it seems to be working.
